apiVersion: v1
data:
  JWT_SECRET: UGdMUGl4MFZ5VUM3NnVBcUJSZHJmR3dVTjF5eG94WDk3b010Y2NlMGg1M1ZveDF4WFI2eUhnQzNIZGxId2p4dVNLeFFaMUU2TWJ0NHJ5d0tJbjFwS3c9PQ==
kind: Secret
metadata:
  creationTimestamp: null
  name: jwt-secret
